# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iio9pUnjSTUCnmaWUY1oSMqZtcr29FTW
"""

from kivy.app import App
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.label import Label
from kivy.uix.button import Button
from kivy.uix.screenmanager import ScreenManager, Screen
from kivy.uix.textinput import TextInput
from kivy.uix.widget import Widget
from kivy.graphics import Color, Rectangle

# Define a widget for setting the background color
class BackgroundWidget(Widget):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        with self.canvas:
            Color(244/255, 194/255, 194/255,1)
            self.rect = Rectangle(size=self.size, pos=self.pos)
        self.bind(size=self.update_rect, pos=self.update_rect)

    def update_rect(self, instance, value):
        self.rect.size = instance.size
        self.rect.pos = instance.pos

# Home Screen
class HomeScreen(Screen):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

        # Add BackgroundWidget
        self.add_widget(BackgroundWidget())

        layout = BoxLayout(orientation='vertical', padding=[50, 50])

        # Title Label
        title_label = Label(text='Home Page', font_size='30sp', size_hint_y=None, height=50)
        layout.add_widget(title_label)

        # Buttons
        button_customer = Button(text='Customer', size_hint_y=None, height=40)
        button_customer.bind(on_press=self.go_to_customer)
        layout.add_widget(button_customer)

        button_admin = Button(text='Admin', size_hint_y=None, height=40)
        button_admin.bind(on_press=self.go_to_admin)
        layout.add_widget(button_admin)

        button_officer = Button(text='Officer', size_hint_y=None, height=40)
        button_officer.bind(on_press=self.go_to_officer)
        layout.add_widget(button_officer)

        self.add_widget(layout)

    def go_to_customer(self, instance):
        self.manager.current = 'customer'

    def go_to_admin(self, instance):
        self.manager.current = 'admin'

    def go_to_officer(self, instance):
        self.manager.current = 'officer'

# Customer Screen
class CustomerScreen(Screen):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

        # Add BackgroundWidget
        self.add_widget(BackgroundWidget())

        layout = BoxLayout(orientation='vertical', padding=[50, 50])

        # Title Label
        title_label = Label(text='Customer Page', font_size='30sp', size_hint_y=None, height=50)
        layout.add_widget(title_label)

        # Form Layout
        form_layout = BoxLayout(orientation='vertical', spacing=10)

        # ID Field
        id_layout = BoxLayout(spacing=10)
        id_label = Label(text='ID:')
        id_layout.add_widget(id_label)
        self.id_input = TextInput(hint_text='Enter ID')
        id_layout.add_widget(self.id_input)
        form_layout.add_widget(id_layout)

        # Name Field
        name_layout = BoxLayout(spacing=10)
        name_label = Label(text='Name:')
        name_layout.add_widget(name_label)
        self.name_input = TextInput(hint_text='Enter Name')
        name_layout.add_widget(self.name_input)
        form_layout.add_widget(name_layout)

        # Address Field
        address_layout = BoxLayout(spacing=10)
        address_label = Label(text='Address:')
        address_layout.add_widget(address_label)
        self.address_input = TextInput(hint_text='Enter Address')
        address_layout.add_widget(self.address_input)
        form_layout.add_widget(address_layout)

        # Sector No. Field
        sector_layout = BoxLayout(spacing=10)
        sector_label = Label(text='Sector No.:')
        sector_layout.add_widget(sector_label)
        self.sector_input = TextInput(hint_text='Enter Sector No.')
        sector_layout.add_widget(self.sector_input)
        form_layout.add_widget(sector_layout)

        # Officer ID Field
        officer_layout = BoxLayout(spacing=10)
        officer_label = Label(text='Officer ID:')
        officer_layout.add_widget(officer_label)
        self.officer_id_input = TextInput(hint_text='Enter Officer ID')
        officer_layout.add_widget(self.officer_id_input)
        form_layout.add_widget(officer_layout)

        # Reservoir ID Field
        reservoir_layout = BoxLayout(spacing=10)
        reservoir_label = Label(text='Reservoir ID:')
        reservoir_layout.add_widget(reservoir_label)
        self.reservoir_id_input = TextInput(hint_text='Enter Reservoir ID')
        reservoir_layout.add_widget(self.reservoir_id_input)
        form_layout.add_widget(reservoir_layout)

        # Number of Connections Field
        connections_layout = BoxLayout(spacing=10)
        connections_label = Label(text='No. of Connections:')
        connections_layout.add_widget(connections_label)
        self.connections_input = TextInput(hint_text='Enter Number of Connections')
        connections_layout.add_widget(self.connections_input)
        form_layout.add_widget(connections_layout)

        # Water Supply Date Field
        water_date_layout = BoxLayout(spacing=10)
        water_date_label = Label(text='Water Supply Date:')
        water_date_layout.add_widget(water_date_label)
        self.water_date_input = TextInput(hint_text='Enter Water Supply Date')
        water_date_layout.add_widget(self.water_date_input)
        form_layout.add_widget(water_date_layout)

        # Bill Field
        bill_layout = BoxLayout(spacing=10)
        bill_label = Label(text='Bill:')
        bill_layout.add_widget(bill_label)
        self.bill_input = TextInput(hint_text='Enter Bill')
        bill_layout.add_widget(self.bill_input)
        form_layout.add_widget(bill_layout)

        layout.add_widget(form_layout)

        # Save Button
        save_button = Button(text='Save', size_hint_y=None, height=40)
        save_button.bind(on_press=self.save_customer)
        layout.add_widget(save_button)

        # Back Button
        back_button = Button(text='Back to Login', size_hint_y=None, height=40)
        back_button.bind(on_press=self.go_to_login)
        layout.add_widget(back_button)

        self.add_widget(layout)

    def save_customer(self, instance):
        # Retrieve and process input values here
        id_value = self.id_input.text
        name_value = self.name_input.text
        address_value = self.address_input.text
        sector_value = self.sector_input.text
        officer_id_value = self.officer_id_input.text
        reservoir_id_value = self.reservoir_id_input.text
        connections_value = self.connections_input.text
        water_date_value = self.water_date_input.text
        bill_value = self.bill_input.text

        # Perform actions with retrieved data (e.g., save to database, display confirmation)
        print(f"Customer details saved:\nID: {id_value}\nName: {name_value}\nAddress: {address_value}\nSector No.: {sector_value}\nOfficer ID: {officer_id_value}\nReservoir ID: {reservoir_id_value}\nNo. of Connections: {connections_value}\nWater Supply Date: {water_date_value}\nBill: {bill_value}")

    def go_to_login(self, instance):
        self.manager.current = 'home'

# Admin Screen
class AdminScreen(Screen):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

        # Add BackgroundWidget
        self.add_widget(BackgroundWidget())

        layout = BoxLayout(orientation='vertical', padding=[50, 50])
        title_label = Label(text='Admin Page', font_size='30sp', size_hint_y=None, height=50)
        layout.add_widget(title_label)

        self.add_widget(layout)

# Officer Screen
class OfficerScreen(Screen):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

        # Add BackgroundWidget
        self.add_widget(BackgroundWidget())

        layout = BoxLayout(orientation='vertical', padding=[50, 50])
        title_label = Label(text='Officer Page', font_size='30sp', size_hint_y=None, height=50)
        layout.add_widget(title_label)

        self.add_widget(layout)

# Main App
class LoginApp(App):
    def build(self):
        sm = ScreenManager()

        sm.add_widget(HomeScreen(name='home'))
        sm.add_widget(CustomerScreen(name='customer'))
        sm.add_widget(AdminScreen(name='admin'))
        sm.add_widget(OfficerScreen(name='officer'))

        return sm

if __name__ == '__main__':
    LoginApp().run()